[package]
name = "ddc-winapi"
version = "0.3.0"
authors = ["arcnmx"]

description = "DDC/CI monitor control on Windows"
keywords = ["ddc", "mccs", "vcp", "vesa"]

documentation = "http://arcnmx.github.io/ddc-winapi-rs/ddc_winapi"
repository = "https://github.com/arcnmx/ddc-winapi-rs"
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "arcnmx/ddc-winapi-rs" }
maintenance = { status = "passively-maintained" }

[dependencies]
ddc = { version = "^0.2.0" }
winapi = { version = "^0.3.5", features = ["windef", "minwindef", "winuser", "physicalmonitorenumerationapi", "lowlevelmonitorconfigurationapi"] }
widestring = "1"
