[package]
name = "ddc-winapi"
version = "0.3.1"
authors = ["arcnmx"]
edition = "2021"

description = "DDC/CI monitor control on Windows"
keywords = ["ddc", "mccs", "vcp", "vesa"]

documentation = "http://arcnmx.github.io/ddc-winapi-rs/ddc_winapi"
repository = "https://github.com/arcnmx/ddc-winapi-rs"
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "arcnmx/ddc-winapi-rs" }
maintenance = { status = "passively-maintained" }

[dependencies]
ddc = { version = "^0.2.0" }
widestring = "^0.4.0"
windows = { version = "0.25", features = ["Win32_Devices_Display", "Win32_Foundation", "Win32_Graphics_Gdi"] }
